### ISSUE TITLE
Date issue

### ISSUE THREAD

**Issue by oscarlgz** [RebirthDB/rebirthdb-ts#1]
Thank you for your work on this library!

https://github.com/RebirthDB/rebirthdb-ts/blob/master/src/response/response-parser.ts#L23

This line of code works fine with dates that have been created by the DB's own date methods (such as r.now()), however if the date was created by Javascript (i.e. new Date() or Date.now()) the driver will return a date a couple of thousand years into the future!

**Comment by ronzeidman** [comment]
In the admin panel you can also see the date in the future? I think the issue is in the creation not the parse. I'll check it.

**Comment by oscarlgz** [comment]
@ronzeidman Yes the stored date is in the future, so you are correct. It's the creation.

**Comment by ronzeidman** [comment]
fixed, you can test the latest release

**Comment by oscarlgz** [comment]
Yes works great, thanks a lot!
